# config.yml

# SciML-Bench
# Copyright © 2021 Scientific Machine Learning Research Group
# Scientific Computing Department, Rutherford Appleton Laboratory
# Science and Technology Facilities Council, UK. 
# All rights reserved.

# This is a configuration file for the sciml-bench.



# Location where the datasets are.
data_mirrors:
    stfc_mirror: "https://s3.echo.stfc.ac.uk"
    osn_mirror: "https://sdsc.osn.xsede.org"

# Download commands - parameterised to servers 
download_commands: 
    download_command1: "aws s3 --no-sign-request --endpoint-url $SERVER sync $DATASET_URI $DATASET_DIR"
    
# Dataset and output directories
directories:
    dataset_root_dir: ~/sciml_bench/datasets
    output_root_dir: ~/sciml_bench/outputs
    models_dir: ~/sciml_bench/models
    docs_dir: ~/sciml_bench/docs


# List of datasets
datasets: 
    mnist:
        end_point: 'sciml-datasets/ts'
        download_command: download_command1
    em_graphene_sim:
        end_point: 'sciml-datasets/ms'
        download_command: download_command1
    dms_sim:
        end_point: 'sciml-datasets/ms'
        download_command: download_command1
    optical_damage_ds1:
        end_point: 'sciml-datasets/ins'
        download_command: download_command1
    inelastic_ds1:
        end_point: 'sciml-datasets/ms'
        download_command: download_command1


# List of benchmarks
benchmarks:

    # Production level benchmarks 
    em_denoise:
        datasets: em_graphene_sim
        dependencies: 'torch, scikit-image'
        types: 'training, inference'
        group: 'science'

    dms_structure:
        datasets: dms_sim
        dependencies: 'torch, scikit-learn, scikit-image'
        types: 'training, inference'
        group: 'science'
    
    optical_damage:
        datasets: optical_damage_ds1
        dependencies: 'tensorflow,scikit-learn,h5py,tqdm'
        types: 'training, inference'
        group: 'science'
        
    inelastic:
        datasets: inelastic_ds1
        dependencies: 'tensorflow, tqdm'
        types: 'training, inference'
        group: 'science'

